services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app # For hot reloading
      - ./data:/app/data
    working_dir: /app
    command: sh -c "go mod tidy && CGO_ENABLED=0 go run main.go"
    environment:
      - GIN_MODE=debug
      - GO111MODULE=on
      - GOOS=linux
      - CGO_ENABLED=0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "9091:5173"
    volumes:
      - ./frontend:/app # For hot reloading
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    environment:
      - VITE_API_URL=http://localhost:9090
    depends_on:
      - backend
