services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "9090:9090"
    volumes:
      - ./backend:/app # For hot reloading
      - ./data:/app/data
    command: go run main.go
    environment:
      - GIN_MODE=debug
      - GO111MODULE=on

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "9091:3000"
    volumes:
      - ./frontend:/app # For hot reloading
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:9090
    command: npm run dev
    depends_on:
      - backend
