version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./data:/app/data
    environment:
      - GIN_MODE=release
      - CGO_ENABLED=0
