services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    command: nginx -g 'daemon off;'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "9090"
    volumes:
      - ./data:/app/data
    environment:
      - GIN_MODE=release
      - CGO_ENABLED=0

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  default:
    name: webman_network
