FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/main .

# Create data directory for SQLite
RUN mkdir -p /app/data

EXPOSE 9090

CMD ["./main"] 